const asyncHandler = require('express-async-handler');
const Alert = require('../models/Alert');
const { sendMail } = require('../utils/sendmail');

// Resolve an alert by id (sets status to 'Resolved')
const resolveAlert = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const alert = await Alert.findById(id);
  if (!alert) {
    res.status(404);
    throw new Error('Alert not found');
  }

  const now = new Date();
  alert.status = 'Resolved';
  alert.resolvedAt = now;
  // compute duration from createdAt to now (ms)
  try {
    if (alert.createdAt) {
      alert.durationMs = now.getTime() - new Date(alert.createdAt).getTime();
    }
  } catch (e) {
    alert.durationMs = null;
  }

  // compute durationStr HH:MM:SS
  if (typeof alert.durationMs === 'number') {
    const totalSeconds = Math.max(0, Math.floor(alert.durationMs / 1000));
    const hours = Math.floor(totalSeconds / 3600);
    const minutes = Math.floor((totalSeconds % 3600) / 60);
    const seconds = totalSeconds % 60;
    const pad = (n) => String(n).padStart(2, '0');
    alert.durationStr = `${pad(hours)}:${pad(minutes)}:${pad(seconds)}`;
  } else {
    alert.durationStr = '00:00:00';
  }

  await alert.save();

  // record system log (best-effort)
  try {
    const { recordLog } = require('../middleware/logger');
    await recordLog({ req, actorType: 'victim', actorId: alert.victimID || null, action: 'alert_resolved', details: `Alert ${alert.alertID} resolved` });
  } catch (e) {
    console.warn('Failed to record alert resolved log', e && e.message);
  }

  res.status(200).json({ success: true, message: 'Alert resolved', data: { id: alert._id, alertID: alert.alertID, resolvedAt: alert.resolvedAt, durationMs: alert.durationMs, durationStr: alert.durationStr } });
});

// List alerts with optional filters (status)
const listAlerts = asyncHandler(async (req, res) => {
  const { status } = req.query;
  const filter = {};
  if (status) filter.status = status;
  const alerts = await Alert.find(filter).sort({ createdAt: -1 }).populate('victimID');
  res.status(200).json({ success: true, data: alerts });
});

module.exports = { resolveAlert, listAlerts };

// Send SOS email containing a Google Maps link to a fixed recipient.
// POST /api/alerts/:id/sos
const sendSOSEmail = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const alert = await Alert.findById(id).populate('victimID');
  if (!alert) {
    res.status(404);
    throw new Error('Alert not found');
  }

  const lat = alert.location?.latitude;
  const lng = alert.location?.longitude;

  if (typeof lat !== 'number' || typeof lng !== 'number') {
    res.status(400);
    throw new Error('Alert does not have valid latitude/longitude');
  }

  const mapsLink = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(lat + ',' + lng)}`;
  const recipient = 'jadenyuki486@gmail.com';
  const subject = `SOS Alert — ${alert.alertID || 'Unknown ID'}`;
  const victimInfo = alert.victimID ? `Victim: ${alert.victimID.victimName || alert.victimID._id}` : 'Victim: unknown';

  const html = `
    <p><strong>Emergency SOS</strong></p>
    <p>${victimInfo}</p>
    <p>Alert ID: <b>${alert.alertID}</b></p>
    <p>Location: <a href="${mapsLink}" target="_blank" rel="noopener noreferrer">${lat}, ${lng}</a></p>
    <p>Time: ${new Date(alert.createdAt).toLocaleString()}</p>
    <hr>
    <p>This message was generated by the VAWCare Barangay Support System.</p>
  `;

  try {
    await sendMail(recipient, subject, html);

    // Record that we notified this contact (best-effort)
    try {
      await alert.addNotifiedContact({
        contactID: `email-${recipient}`,
        name: recipient,
        contactNumber: '',
        notificationTime: new Date(),
        notificationStatus: 'Sent'
      });
    } catch (e) {
      console.warn('Failed to record notified contact', e && e.message);
    }

    res.status(200).json({ success: true, message: 'SOS email sent' });
  } catch (err) {
    console.error('Failed to send SOS email', err);
    res.status(500).json({ success: false, message: 'Failed to send SOS email' });
  }
});

// export additional function
module.exports = { resolveAlert, listAlerts, sendSOSEmail };
